const persona = {
  nombre: "Carlos",
  apellido: "Ojeda",
  edad: 30,
  pais: "Mexico",
  profesion: "Dev",
  sabeManejar: true,
  mascotas: ["chiquitin", "mariposa", "negro"],
  hobbies: ["leer", "estudiar", "programar"],
  tocaIntrumentos: false,
  nivelIngles: "A2",
  ciudad: "Santiago astata",
  redesSociales: ["facebook", "instagram", "youtube"],
  peliculasFavoritas: ["titanic", "la momia", "el rey del barrio"],
  comidasFavoritas: ["empanadas", "tacos", "tortas"],
  sabeCocinar: true,
  diaDeLaSemanaFavorito: "Domingo",
  objetivosPorCumplir: [
    "Ser desarrollador FullStack Js",
    "Trabajar como Dev",
    "Tener mi propia motocicleta",
    "Tener mi propia Casa",
  ],
};
